import {
  collection,
  addDoc,
  getDocs,
  deleteDoc,
  doc,
  getDoc,
  setDoc,
  serverTimestamp,
} from "firebase/firestore";
import { db } from "../components/firebase";

const CACHE_DOC = "feed_cache_meta";
const CACHE_DURATION = 7 * 24 * 60 * 60 * 1000; // 7 days

const APP_CONTEXT = `
You are writing content for MLA Math App — a math learning app with these features:
- Topics: algebra, calculus, polynomials, graphing, exponential functions, systems of equations
- Formula reference sheets
- Practice questions with difficulty levels (Easy, Moderate, Hard)
- AI-powered calculator that solves step by step
- Progress tracking with charts
- History of studied topics
- Theme customization (colors, dark/light mode)
- User levels: Beginner, Intermediate, Advanced
- Search panel with trending math topics
- Upcoming features: gamification, multiplayer math challenges, AI tutor chat
`;

export async function generateFeedIfNeeded() {
  try {
    // Check cache
    const cacheRef = doc(db, "homepage_feed", CACHE_DOC);
    const cacheSnap = await getDoc(cacheRef);

    if (cacheSnap.exists()) {
      const lastGenerated = cacheSnap.data().lastGenerated?.toMillis?.() || 0;
      const isExpired = Date.now() - lastGenerated > CACHE_DURATION;
      if (!isExpired) return; // Still fresh, skip generation
    }

    // Call OpenAI
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${import.meta.env.VITE_OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: "gpt-3.5-turbo",
        messages: [
          {
            role: "user",
            content: `${APP_CONTEXT}

Generate content for a math learning app home screen.
Return ONLY a JSON object with this structure:
{
  "tips": [
    { "title": "short title", "body": "one sentence tip about how to use the app" }
  ],
  "updates": [
    { "title": "short title", "body": "one catchy sentence about a feature or upcoming feature" }
  ]
}

Rules:
- Generate exactly 6 tips and 6 updates
- Tips should teach users how to use app features
- Updates should announce features or tease upcoming ones
- Keep each body under 15 words
- Be catchy and engaging
- Return ONLY valid JSON, no explanation`,
          },
        ],
      }),
    });

    const data = await response.json();
    const result = JSON.parse(data.choices[0].message.content);

    // Delete old AI-generated docs (keep manual ones by checking author)
    const feedSnap = await getDocs(collection(db, "homepage_feed"));
    const deletePromises = feedSnap.docs
      .filter((d) => d.data().author === "AI" && d.id !== CACHE_DOC)
      .map((d) => deleteDoc(doc(db, "homepage_feed", d.id)));
    await Promise.all(deletePromises);

    // Save new tips
    const tipPromises = result.tips.map((tip) =>
      addDoc(collection(db, "homepage_feed"), {
        title: tip.title,
        body: tip.body,
        category: "Tip",
        author: "AI",
        timestamp: serverTimestamp(),
      })
    );

    // Save new updates
    const updatePromises = result.updates.map((update) =>
      addDoc(collection(db, "homepage_feed"), {
        title: update.title,
        body: update.body,
        category: "Update",
        author: "AI",
        timestamp: serverTimestamp(),
      })
    );

    await Promise.all([...tipPromises, ...updatePromises]);

    // Update cache timestamp
    await setDoc(cacheRef, {
      lastGenerated: serverTimestamp(),
      author: "cache",
    });

    console.log("✅ Feed generated by AI");
  } catch (err) {
    console.error("❌ Failed to generate feed:", err);
    // Silently fail — existing Firestore data will show as fallback
  }
}